export default {
    "menu": [{
		name: "系统首页",
		url: "/index",
		checked: false
	}, {
		name: "多站点对比",
		url: "/compare1",
		checked: false
	}, {
		name: "单站点对比",
		url: "/compare2",
		checked: false
	}, {
		name: "昼夜对比",
		url: "/compare3",
		checked: false
	}, {
		name: "实时数据",
		url: "/realtime",
		checked: false
	}, {
		"name": "单站点查询",
		"url": "/singlepage",
		"checked": false
	},{
		"name": "综合查询",
		"url": "/comprehensive",
		"checked": false
	},{
		"name": "流动站点轨迹图",
		"url": "/trackmap",
		"checked": false
	}, {
		"name": "用户信息管理",
		"url": "/userinfo",
		"checked": false
	}, {
		"name": "角色信息管理",
		"url": "/userrole",
		"checked": false
	}, {
		"name": "01-报表",
		"url": "/report1",
		"checked": false
	}, {
		"name": "02-报表",
		"url": "/report2",
		"checked": false
	}, {
		"name": "03-报表",
		"url": "/report3",
		"checked": false
	}, {
		"name": "04-报表",
		"url": "/report4",
		"checked": false
	}, {
		"name": "05-报表",
		"url": "/report5",
		"checked": false
	}, {
		"name": "06-报表",
		"url": "/report6",
		"checked": false
	}, {
		"name": "07-报表",
		"url": "/report7",
		"checked": false
	}, {
		"name": "08-报表",
		"url": "/report8",
		"checked": false
	}, {
		"name": "09-报表",
		"url": "/report9",
		"checked": false
	}, {
		"name": "噪声点管理",
		"url": "/noise",
		"checked": false
	}, {
		"name": "流动站点管理",
		"url": "/noisecar",
		"checked": false
	}]
}
